tap_install:
    sensitive_values:
        tap_gui:
            app_config:
                backend:
                    database:
                        client: ENC[AES256_GCM,data:55U=,iv:MIfbqaDlAjOdwtvKcdGcLpPgvwJEve7qnp07ywLzksY=,tag:igedv2czvny7tuaLxpu2hA==,type:str]
                        connection:
                            host: ENC[AES256_GCM,data:Km4LBUHxf5d1TyZbijSf13R4x6kdRszJdD6RQhgpqfvpBlTw,iv:vKZm71Q3AGQCDGQpNKf9e3SfZj1sSNs070G/Sc1rZvE=,tag:AMFOmKc5bJ5PGTaV0/fH0w==,type:str]
                            port: ENC[AES256_GCM,data:v2smxw==,iv:ovQYXi2/rE+PRD6828O9a+thrH2qBo1rdml3g6PFn+E=,tag:RNOtSXSvhQT3KqSxajJTlg==,type:int]
                            user: ENC[AES256_GCM,data:1in1vZidR0o=,iv:XSwix8x8GPJrC44WHB37UkhGZsnTykpPNrp3OEKtocg=,tag:YkTS5+L/qrPBkZfhcKYeZA==,type:str]
                            password: ENC[AES256_GCM,data:VdmkkRcLiSIb7epE,iv:D0YdSRvrAjzXZnt1+8qW8FYg7ySGDgf1JvZArHhgqwA=,tag:bqzDvF58wBXBWz1K6ey30w==,type:str]
                            ssl:
                                rejectUnauthorized: ENC[AES256_GCM,data:QCcKiVY=,iv:h9XCjveiLmoEJ6Eg0Y+g621vd5RCKFmg2bP4ovLzfYg=,tag:N6bzF2qjpOVPkB2i5FEuNg==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12a9356x4078gw5nmvwl5w3kv9ncfledkuy9jd4wph7gxhtr98cdqlalse9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSckt2dExScGJjbm9zYkhS
            KzN1UytUV3JzZW10bVZHZEN6UkpOdzBuRmxNCjFrYzd0VCtzdCs4aWFYa0NVaGNH
            NHJoRTRPRUdBb1Y1R0lMQzdKYnI5QWcKLS0tIDBNZlVrTFo5RjdjTmhxN1l4bVpi
            TWZRNDhyeVphM3ZucjM2VU80ZTdIeE0KlyGrarFfiC3EDCUJGZm24qSjhnfjBjQg
            JQU4q5DyJKE9m8kFF9B6xCzmVw4IXiwwMwHzut53nSQBDx0uUbjT3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-23T20:27:13Z"
    mac: ENC[AES256_GCM,data:WqqrThx3SnPRFGfiFAbwzy5IESztYym2To2pmFKOQg88g+ZkcgbmoILVU2ohgEqa04Z5wFG59LKz7sEt/swzf26YGY4US7zAJ/J7ag2V0IpP+x5xjgAdohUr5cyNnTdiWjTc7kfjbzffRch5wiNVqwKV6SSpvxmv75RqlcbN7Pg=,iv:hrZoOdUANT47aKGdSRLnv6g6kpHbzPKF30zVD7Xp+tg=,tag:sdqArMDFdBw7Kn2vXQ044Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
