tap_install:
  values:
    profile: view

    shared:
      ingress_domain: tap.withtanzu.com
      ingress_issuer: letsencrypt

    excluded_packages:
    - learningcenter.tanzu.vmware.com
    - workshops.learningcenter.tanzu.vmware.com

    ceip_policy_disclosed: true

    appliveview:
      ingressEnabled: true

    tap_gui:
      deployment:
        replicas: 3
      metadataStoreAutoconfiguration: true
      app_config:
        app:
          baseUrl: https://console.tap.withtanzu.com
        backend:
          baseUrl: https://console.tap.withtanzu.com

    package_overlays:
    - name: tap-telemetry
      secrets:
      - name: overlay-disable-tap-telemetry
    - name: tap-gui
      secrets:
      - name: overlay-add-tap-gui-alias
      - name: overlay-patch-tap-gui-timeout
