#! Create a Secret with Git credentials:
#! values are copied from a Secret located in another namespace.
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: git-credentials
  annotations:
    tekton.dev/git-0: https://github.com
spec:
  fromNamespace: tap-secrets
