apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: clusters/tap-iterate/cluster-config/config/shared
  contents:
  - path: .
    includePaths:
    - "**/*.yaml"
    directory:
      path: clusters/shared/config

- path: clusters/tap-build/cluster-config/config/shared
  contents:
  - path: .
    includePaths:
    - "**/*.yaml"
    directory:
      path: clusters/shared/config

- path: clusters/tap-run-az/cluster-config/config/shared
  contents:
  - path: .
    includePaths:
    - "**/*.yaml"
    directory:
      path: clusters/shared/config

- path: clusters/tap-view/cluster-config/config/shared
  contents:
  - path: .
    includePaths:
    - "**/*.yaml"
    excludePaths:
    - "**/tap-gui-viewer-service-account-rbac.yaml"
    directory:
      path: clusters/shared/config
