apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: clusters/shared/config/addons/otel
  contents:
  - path: .
    githubRelease:
      slug: open-telemetry/opentelemetry-operator
      tag: v0.91.0
      disableAutoChecksumValidation: true
      assetNames:
      - opentelemetry-operator.yaml

- path: clusters/tap-iterate/cluster-config/config/shared
  contents:
  - path: .
    includePaths:
    - "**/*.yaml"
    excludePaths:
    - "addons/amr/**"
    directory:
      path: clusters/shared/config

- path: clusters/tap-build/cluster-config/config/shared
  contents:
  - path: .
    includePaths:
    - "**/*.yaml"
    excludePaths:
    - "addons/acs/**"
    - "addons/otel/**"
    - "addons/rmq/**"
    - "addons/scg/**"
    directory:
      path: clusters/shared/config

- path: clusters/tap-run-az/cluster-config/config/shared
  contents:
  - path: .
    includePaths:
    - "**/*.yaml"
    directory:
      path: clusters/shared/config

- path: clusters/tap-run-gke/cluster-config/config/shared
  contents:
  - path: .
    includePaths:
    - "**/*.yaml"
    directory:
      path: clusters/shared/config

- path: clusters/tap-view/cluster-config/config/shared
  contents:
  - path: .
    includePaths:
    - "**/*.yaml"
    excludePaths:
    - "addons/**"
    - "**/tap-gui-viewer-service-account-rbac.yaml"
    directory:
      path: clusters/shared/config
