apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: tap-gui-alias
  namespace: tap-gui
spec:
  routes:
  - services:
    - name: server
      port: 7000
    timeoutPolicy:
      idle: 30s
      response: 30s
  virtualhost:
    fqdn: console.tap.withtanzu.com
    tls:
      secretName: tap-gui-cert
