apiVersion: v1
kind: Secret
metadata:
  name: app-overlays
stringData:
  overlay-app-probeless.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind":"Deployment"}), expects="0+"
    ---
    spec:
      template:
        spec:
          containers:
          #@overlay/match by=overlay.index(0)
          - name: workload
            #@overlay/remove
            livenessProbe:
            #@overlay/remove
            readinessProbe:
            #@overlay/remove
            startupProbe:
