apiVersion: v1
kind: Secret
metadata:
  name: overlay-configure-cors-tap-gui
  namespace: tap-install
stringData:
  overlay-configure-cors-tap-gui.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind":"HTTPProxy", "metadata": {"name":"tap-gui"}}),expects=1
    ---
    spec:
      #@overlay/match missing_ok=True
      virtualhost:
        #@overlay/match missing_ok=True
        corsPolicy:
          allowOrigin:
          - "*" 
          allowMethods:
          - GET
          - POST
          - OPTIONS
          allowHeaders:
          - authorization
          - cache-control
          exposeHeaders:
          - Content-Length
          - Content-Range
          maxAge: "10m"
