apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tanzu-rabbitmq-repo
  namespace: tap-install
spec:
  fetch:
    imgpkgBundle:
      image: tdkhub.azurecr.io/tanzu-rabbitmq:1.5.0
