---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: store-auth-token
  namespace: tap-secrets
  annotations:
    kapp.k14s.io/change-group: pkgi
    kapp.k14s.io/update-strategy: fallback-on-replace
stringData:
  auth_token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkVvWXNFOUhFeG1zNHo0bkdjcnF1M3FvendHakNCZDM0QjdkV09ZUUJfbFEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJtZXRhZGF0YS1zdG9yZSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJtZXRhZGF0YS1zdG9yZS1yZWFkLXdyaXRlLWNsaWVudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJtZXRhZGF0YS1zdG9yZS1yZWFkLXdyaXRlLWNsaWVudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjU3MzIxM2EzLWU0MTAtNDk2Zi1hMDBkLWFlZTRkODUyY2U5MiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDptZXRhZGF0YS1zdG9yZTptZXRhZGF0YS1zdG9yZS1yZWFkLXdyaXRlLWNsaWVudCJ9.v7B0ReAglJjTml-Rxntbx33pq8UnM_n1-6gXCk0RLWNUUfcoZfvdB_Hdza9JcxZhqjBtEBKjUBP8fITDGqYCpLaQjE6FftBAnQ-v7lE63w397Gw8yj-5YhNsbOT_q0iR9RTW3D5b1SL_thAamAqDSAOyR5EH0qW0oBhajq2mmTot2UYEzzM1LlYOjJ3hwW6HBEvgoGcuy2B09Tr1HXR_MdSO8VzT-xCvslJPqfNgzamwjPA1YBY33o8LaGIEEZLeuwqFsTveZeBitlSYaEV-4t4xKlX113qM9RzIwWf3H2VlaE-SIm0cpE2ytO4uudFHwccSKeSqcOm2TIMNS7R9gfU95y-4klHyYoOb_ESUZSwZIrzesedy7A9sMKX0k7i6mXiY30IAafjZZqskQ51XzqAJcAzH1mX2ocxtpDcWx9HIYneXZi9F4mAEwAyZ-sNK5lRm2zX4xo-lB1MHSxDkIKqZIYtDNN_A5DGLQ2ikjWadXb3lhkIWJAHPxYu-xKIpEx3lOCeMrYD2veaInNQDy63t21TU_oAmlzWjL6p_J0FYal90oVLNUdUbg9HFaFSEU1j3geepOqZGWouNhTRiI_gunHmiZLpL1oZIB5xdt1zRWVPL_jOEmPLGuHNbXYWowJYPprY9GNKqLhxeN0AIjtCBg9mNnfAX3RG9mmxprzU
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: store-auth-token
  namespace: tap-secrets
  annotations:
    kapp.k14s.io/change-group: pkgi
spec:
  toNamespaces:
  - '*'
