tap_install:
  values:
    profile: run

    shared:
      ingress_domain: az.run.withtanzu.com
      ingress_issuer: letsencrypt

    ceip_policy_disclosed: true

    appliveview_connector:
      activateSensitiveOperations: true
      backend:
        host: appliveview.tap.withtanzu.com
        ingressEnabled: true

    api_auto_registration:
      tap_gui_url: https://console.tap.withtanzu.com
      cluster_name: tap-run-az

    package_overlays:
    - name: tap-telemetry
      secrets:
      - name: overlay-disable-tap-telemetry
    - name: cnrs
      secrets:
      - name: overlay-cnrs-enable-fieldref

    cnrs:
      domain_template: '{{.Name}}.{{.Domain}}'

    namespace_provisioner:
      controller: true
      overlay_secrets:
      - name: overlay-disable-limitrange
        namespace: tap-install
        create_export: true
      additional_sources:
      - git:
          url: https://github.com/alexandreroman/tap-demo-kit-gitops.git
          ref: origin/main
          subPath: clusters/tap-run-az/namespace-provisioner/resources
