apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  annotations:
    kapp.k14s.io/change-group: cert-manager/cluster-issuer
    kapp.k14s.io/change-rule: "upsert after upserting cert-manager"
spec:
  acme:
    email: aroman@vmware.com
    privateKeySecretRef:
      name: letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: contour
