apiVersion: sso.apps.tanzu.vmware.com/v1alpha1
kind: AuthServer
metadata:
  name: login
  namespace: sso
  labels:
    sso.apps.tanzu.vmware.com/env: iterate
  annotations:
    sso.apps.tanzu.vmware.com/allow-client-namespaces: "*"
    sso.apps.tanzu.vmware.com/allow-unsafe-issuer-uri: ""
    sso.apps.tanzu.vmware.com/allow-unsafe-identity-provider: ""
    sso.apps.tanzu.vmware.com/allow-unsafe-cors: ""
spec:
  replicas: 1
  cors:
    allowAllOrigins: true
  tokenSignature:
    signAndVerifyKeyRef:
      name: authserver-signing-key
  tls:
    issuerRef:
      name: letsencrypt
      kind: ClusterIssuer
  identityProviders:
  - name: auth0
    openID:
      issuerURI: https://dev-58yj7efmew5mc2rq.eu.auth0.com
      clientID: DQxUTXBUETivouAvdOYkabkKy2XgqatN
      clientSecretRef:
        name: auth0-openid-client-secret
      scopes:
      - openid
      - email
      - profile
      authorizationUri: https://dev-58yj7efmew5mc2rq.eu.auth0.com/authorize
      tokenUri: https://dev-58yj7efmew5mc2rq.eu.auth0.com/oauth/token
      jwksUri: https://dev-58yj7efmew5mc2rq.eu.auth0.com/.well-known/jwks.json
      userinfoUri: https://dev-58yj7efmew5mc2rq.eu.auth0.com/userinfo
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: RSAKey
metadata:
  name: authserver-signing-key
  namespace: sso
spec:
  secretTemplate:
    type: Opaque
    stringData:
      key.pem: $(privateKey)
      pub.pem: $(publicKey)
