apiVersion: sso.apps.tanzu.vmware.com/v1alpha1
kind: AuthServer
metadata:
  name: login
  namespace: sso
  labels:
    name: appsso
  annotations:
    sso.apps.tanzu.vmware.com/allow-client-namespaces: "*"
    sso.apps.tanzu.vmware.com/allow-unsafe-issuer-uri: ""
    sso.apps.tanzu.vmware.com/allow-unsafe-identity-provider: ""
spec:
  replicas: 1
  tokenSignature:
    signAndVerifyKeyRef:
      name: authserver-signing-key
  tls:
    issuerRef:
      name: letsencrypt
      kind: ClusterIssuer
  identityProviders:
  # - name: github
  #   openID:
  #     issuerURI: https://github.com/login/oauth/authorize
  #     clientID: e8ccb32916f021c53683
  #     clientSecretRef:
  #       name: github-openid-client-secret
  #     scopes:
  #     - user:email
  #     authorizationUri: https://github.com/login/oauth/authorize
  #     tokenUri: https://github.com/login/oauth/access_token
  # - name: okta
  #   openID:
  #     issuerURI: https://dev-66296142.okta.com/oauth2/default
  #     clientID: 0oaai5rllrN3442Dl5d7
  #     clientSecretRef:
  #       name: github-openid-client-secret
  #     scopes:
  #     - openid
  #     - email
  #     authorizationUri: https://dev-66296142.okta.com/oauth2/default/v1/authorize
  #     tokenUri: https://dev-66296142.okta.com/oauth2/default/v1/token
  #     jwksUri: https://dev-66296142.okta.com/oauth2/default/v1/keys
  - name: auth0
    openID:
      issuerURI: https://dev-58yj7efmew5mc2rq.eu.auth0.com
      clientID: DQxUTXBUETivouAvdOYkabkKy2XgqatN
      clientSecretRef:
        name: auth0-openid-client-secret
      scopes:
      - openid
      - email
      - profile
      authorizationUri: https://dev-58yj7efmew5mc2rq.eu.auth0.com/authorize
      tokenUri: https://dev-58yj7efmew5mc2rq.eu.auth0.com/oauth/token
      jwksUri: https://dev-58yj7efmew5mc2rq.eu.auth0.com/.well-known/jwks.json
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: RSAKey
metadata:
  name: authserver-signing-key
  namespace: sso
spec:
  secretTemplate:
    type: Opaque
    stringData:
      key.pem: $(privateKey)
      pub.pem: $(publicKey)
