apiVersion: ENC[AES256_GCM,data:hYM=,iv:VGQXnqaGD1Pr8m4Pq7XU7BsVf2Ux24qQ4Ynap9JitSo=,tag:7Dtsl7GKAXGuq35xRv5LAQ==,type:str]
kind: ENC[AES256_GCM,data:/HBOops3,iv:oT0ZrVyzzPq1KeS8OcIU8L1Z9AHnwJZs//t/v6E1Ba0=,tag:OmPijv0B8EG/YpBh5M9R1A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:7Vu3azltDpdHse6EL7YmePolbGCFVebxs2A=,iv:2sS3iLbTq8vXMdDbXfi/8fVxGFdciXoSMyPeRJFE68g=,tag:AfwB8NOa8Kl/qydgrkJsPw==,type:str]
    namespace: ENC[AES256_GCM,data:5MMZ,iv:3wQJ24ZTM7lv56JAIAzQHjbSrAJDGZj6rp9ZIQ/BPbI=,tag:6a8qUbBJS+MJcinoIIQ3MA==,type:str]
type: ENC[AES256_GCM,data:HbWtHbO8,iv:Tv0lkBvYqwCa1mMdHcRT+ObnktkwJL6iyVSZ6ORUwQs=,tag:r0YblndsJdVgofbUvBhoOA==,type:str]
stringData:
    clientSecret: ENC[AES256_GCM,data:2T3CzmBPESFfZkVhatgyFCOId8U273I/2+Y8k/NFLPlI8rkIh53zgshJQUJiLW+M57SwqHIZA0eOCTsJdIjcCQ==,iv:tkJxKRF/pvZnWboNOll/VVENdSG/lsb6kYR8rZ3RTUI=,tag:kkkfuYuwAB6yxuReuVtDpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12a9356x4078gw5nmvwl5w3kv9ncfledkuy9jd4wph7gxhtr98cdqlalse9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bzBDeGJtRnAxQk1HZ0Fh
            WWJRckxCdGFHbWI0bmRSSThOZzNlTXZrcDFBCkRjYTJFMGV3Q09WeUNRa0Mxa2xH
            dW1BYml4cGhNQXNrMitEVkFpaW1QWDAKLS0tIDBuYWExTlFrY2RwV3JmTVVyN0pr
            TG50ZEpwMmlKd0RHSC9zRnBOcWN6RTgKzEAFZ4Xi0c4c0A5enW5D8XtUTwPu+D/Q
            JZuFenrhU60YKQyhZ1JOfQfjdh0ES+ckujluoXI+NkaaMUP7fHzyYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-24T23:35:28Z"
    mac: ENC[AES256_GCM,data:nLvn0cBgDbm613Uyb/NFELEFTrfBrkdXj94t2zCKNBcjp4ckB4OG0k0pSCQXKtAhpvrwYHAEZA8u5MjiWBIjx5kiAfg6RdRv34SV9ufC86QAAhVVEXXmUAt1uOJjlZlPw+lcB+HEc7vF6uj9uJqJIp1v0+n3bJ1QLz9YV9i+Jnc=,iv:lLGgZks6W7xJBk/Yr+SQn3Mf/wCDMuUTxagvnjXSme8=,tag:9YbNWSaNQ2Af13rY4Kc7bg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
