apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: amr-observer-edit-token
  namespace: tap-secrets
  annotations:
    kapp.k14s.io/change-group: pkgi
spec:
  toNamespaces:
  - amr-observer-system
