apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: scg-operator
  namespace: tap-install
spec:
  packageRef:
    refName: spring-cloud-gateway.tanzu.vmware.com
    versionSelection:
      constraints: 2.0.3
      prereleases: {}
  serviceAccountName: tap-install-sa
