tap_install:
  values:
    profile: build

    shared:
      ingress_domain: build.withtanzu.com
      ingress_issuer: ""

    excluded_packages:
    - contour.tanzu.vmware.com

    ceip_policy_disclosed: true

    supply_chain: testing_scanning
    ootb_supply_chain_testing_scanning:
      gitops:
        ssh_secret: git-credentials
        commit_message: Commit by TAP Supply Chain
        username: tap-demo-kit
        email: tap-demo-kit@vmware.com
        server_address: https://github.com
        repository_owner: alexandreroman
        repository_name: tap-demo-kit-apps
        branch: main

    grype:
      namespace: "default"
      targetImagePullSecret: "registry-credentials"
      metadataStore:
        url: https://metadata-store.tap.withtanzu.com
        caSecret:
          name: store-ca-cert
          importFromNamespace: tap-secrets
        authSecret:
          name: store-auth-token
          importFromNamespace: tap-secrets

    springboot_conventions:
      autoConfigureActuators: true

    package_overlays:
    - name: tap-telemetry
      secrets:
      - name: overlay-disable-tap-telemetry
    - name: ootb-templates
      secrets:
      - name: overlay-ootb-supply-chain-kpack

    namespace_provisioner:
      controller: false
      gitops_install:
        url: https://github.com/alexandreroman/tap-demo-kit-gitops.git
        ref: origin/main
        subPath: clusters/tap-build/namespace-provisioner/namespaces
      additional_sources:
      - git:
          url: https://github.com/alexandreroman/tap-demo-kit-gitops.git
          ref: origin/main
          subPath: clusters/tap-build/namespace-provisioner/resources
      default_parameters:
        supply_chain_service_account:
          secrets:
          - git-credentials
