apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: acs
  namespace: tap-install
spec:
  packageRef:
    refName: application-configuration-service.tanzu.vmware.com
    versionSelection:
      constraints: ">= 2.0.0"
      prereleases: {}
  serviceAccountName: tap-install-sa
