apiVersion: v1
kind: Secret
metadata:
  name: overlay-disable-limitrange
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: pkgi
stringData:
  overlay-disable-limitrange.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind": "LimitRange"}), expects="0+"
    #@overlay/remove
    ---
