apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: git-credentials
  annotations:
    tekton.dev/git-0: https://github.com
    kapp.k14s.io/update-strategy: fallback-on-replace
spec:
  fromNamespace: tap-secrets
