apiVersion: v1
kind: Secret
metadata:
  name: overlay-configure-cors-tap-gui
  namespace: tap-install
stringData:
  tap-gui-timeout.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind": "HTTPProxy", "metadata": {"name": "tap-gui"}})
    ---
    spec:
      #@overlay/match-child-defaults missing_ok=True
      virtualhost:
        corsPolicy:
          allowCredentials: true
          allowPrivateNetwork: true
          allowOrigin:
          - "*"
          allowMethods:
          - GET
          - POST
          - OPTIONS
          - DELETE
          - HEAD
          allowHeaders:
          - authorization
          - cache-control
