tap_install:
  values:
    profile: iterate

    shared:
      ingress_domain: apps.withtanzu.com
      ingress_issuer: ""

    ceip_policy_disclosed: true

    supply_chain: basic
    ootb_supply_chain_basic:
      registry:
        server: tdkhub.azurecr.io
        repository: tanzu-application-platform/dev/workloads
      gitops:
        ssh_secret: git-credentials

    local_source_proxy:
      repository: tdkhub.azurecr.io/tanzu-application-platform/dev/workload
      push_secret:
        name: lsp-credentials
        namespace: tap-secrets
      pull_secret:
        name: lsp-credentials
        namespace: tap-secrets

    api_auto_registration:
      replicas: 0

    appliveview_connector:
      activateSensitiveOperations: true
      backend:
        host: appliveview.tap.withtanzu.com
        ingressEnabled: true

    springboot_conventions:
      autoConfigureActuators: true

    package_overlays:
    - name: tap-telemetry
      secrets:
      - name: overlay-disable-tap-telemetry
    - name: cnrs
      secrets:
      - name: overlay-cnrs-enable-fieldref
    - name: ootb-templates
      secrets:
      - name: overlay-ootb-supply-chain-kpack

    namespace_provisioner:
      controller: false
      gitops_install:
        url: https://github.com/alexandreroman/tap-demo-kit-gitops.git
        ref: origin/main
        subPath: clusters/tap-iterate/namespace-provisioner/namespaces
      additional_sources:
      - git:
          url: https://github.com/alexandreroman/tap-demo-kit-gitops.git
          ref: origin/main
          subPath: clusters/tap-iterate/namespace-provisioner/resources
