apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: apps
  namespace: tanzu-sync
  annotations:
    kapp.k14s.io/change-rule.0: upsert after upserting pkgi
spec:
  serviceAccountName: sync-sa
  fetch:
  - git:
      url: https://github.com/alexandreroman/tap-demo-kit-apps.git
      ref: origin/main
      subPath: clusters/tap-run-az
  template:
  - sops:
      age:
        privateKeysSecretRef:
          name: sync-age-identity
  - ytt: {}
  deploy:
  - kapp:
      rawOptions: ["--dangerous-allow-empty-list-of-resources=true"]
