#! Test pipeline used when ootb-supply-chain-testing or ootb-supply-chain-testing-scanning is enabled.
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-pipeline-java
  labels:
    apps.tanzu.vmware.com/pipeline: test
    apps.tanzu.vmware.com/language: java
  annotations:
    kapp.k14s.io/create-strategy: fallback-on-update
spec:
  params:
  - name: source-url
  - name: source-revision
  tasks:
  - name: test
    params:
    - name: source-url
      value: $(params.source-url)
    - name: source-revision
      value: $(params.source-revision)
    taskSpec:
      params:
      - name: source-url
      - name: source-revision
      steps:
      - name: test
        image: ghcr.io/alexandreroman/maven-gradle:17
        script: |-
          cd `mktemp -d`
          wget -qO- $(params.source-url) | tar xvz -m
          SKIP=".skiptests"
          if [ -f "$SKIP" ]; then
            echo "Skipping tests"
            exit 0
          fi
          MVN="pom.xml"
          GRADLE="build.gradle"
          if [ -f "$MVN" ]; then
            mvn --batch-mode --no-transfer-progress verify
          elif [ -f "$GRADLE" ]; then
            gradle test
          else
            echo "This Java workload does not use Maven or Gradle: cannot run tests."
          fi
        volumeMounts:
        - mountPath: /var/run/
          name: dind-socket
      sidecars:
      - image: docker:dind
        name: docker
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/run/
          name: dind-socket
      volumes:
      - name: dind-socket
        emptyDir: {}
